# 2015-07-23 RICHARD:
# THIS IS A SAMPLE FOR social_keys.yml which is git-ignored as it should be, because it will have your keys in it.
# REMEMBER TO COPY THIS FILE TO social_keys.yml AND CHANGE THE KEYS IN THERE TO MATCH YOURS.
development:
  facebook_key: "535402053276201"
  facebook_secret: "5ed73b8b972476169a1d403de82b107d"

  twitter_key: "Y66S6O3uCzd5SBRqFk3k0cKVR"
  twitter_secret: "ROuAmXNhdxs1oUbEPucEVg0tRWfWYBUgpm7GiI8C9kVxIpsNtC"

  github_key: "dc762caaea1375dd897e"
  github_secret: "809660006d27faad2c626514deea0941abbb87d8"

  # linkedin_key: "YOUR_KEY"
  # linkedin_secret: "YOUR_SECRET3"

  # google_key: "YOUR_KEY"
  # google_secret: "YOUR_SECRET"

production:
  facebook_key: "535395039943569"
  facebook_secret: "71f1bf8f81cc10dc41549e3cba24413e"

  twitter_key: "Y66S6O3uCzd5SBRqFk3k0cKVR"
  twitter_secret: "ROuAmXNhdxs1oUbEPucEVg0tRWfWYBUgpm7GiI8C9kVxIpsNtC"

  github_key: "dc762caaea1375dd897e"
  github_secret: "809660006d27faad2c626514deea0941abbb87d8"
  #
  # linkedin_key: "YOUR_KEY"
  # linkedin_secret: "YOUR_SECRET"
  #
  # google_key: "YOUR_KEY"
  # google_secret: "YOUR_SECRET"
